### ISSUE TITLE
Create configuration spreadsheets for a DHIS2 implementation

### ISSUE THREAD

**Issue by gilliankerr** [LogicalOutcomes/dhis2-templates#1]
We are developing a set of Excel spreadsheets that will define the configuration for a simple DHIS2 instance. It will include worksheets for organizational units, users, including roles and permissions, indicators, data elements, option sets and so on. We're looking for help to expand their functionality, including:
- Data validation checks
- Rules for programs in the individual tracker (e.g., if client is over 18 years old, refer her to an educational program)
- Facilities registries 
- Mapping

We will also need a way to upload these spreadsheets to DHIS2 in a format that will support complex relationships between elements.

**Comment by saragaudon** [comment]
Out of date / also we're not using this board.
