### ISSUE TITLE
Trouble accessing the resources (Templates)

### ISSUE THREAD

**Issue by adam-je** [LogicalOutcomes/dhis2-templates#2]
**I've had trouble learning DHIS, especially because I need to use it as an M&E platform in a new context. Your tutorials offer some glimmer of hope but I'm quite stuck because I cannot access the templates. I have downloaded the Offline version (windows), and tried to use the online version, both present unique challenges.**

On the web I cannot download the Templates, or copy and paste (either Ctrl+C/V or Right-Click-Copy/Paste) them into my own OneNote 2013 (desktop). Attachment: 

![paste](https://cloud.githubusercontent.com/assets/7912989/16176796/93719700-3618-11e6-9657-49aca5ef75e1.JPG)

Attempting to download (online) gives the following error:

![download err](https://cloud.githubusercontent.com/assets/7912989/16176810/8cd40904-3619-11e6-9d47-07fad6fe9847.JPG)

Offline I keep getting the signin dialog to the collaboration workspace whenever I try to access the links to the Templates. Attachment:

![sign-in issues](https://cloud.githubusercontent.com/assets/7912989/16176802/cc0e060c-3618-11e6-952e-e16281a941c5.JPG)

What could be the issue here?

**Comment by adam-je** [comment]
[Solution] 

Using windows 10 with Office 2013 installed, I had to synchronise the downloaded OneNote Notebook within **OneNote 2013** over **OneCloud** and open it from **OneNote App** (incl. as Windows 10 app). After opening all seems fine.

**Comment by NicholasKoySantillo** [comment]
good to know, thanks! 

We will archive this solution and add it to our roadmap
