### ISSUE TITLE
Skype contacts not included in the Notebook

### ISSUE THREAD

**Issue by adam-je** [LogicalOutcomes/dhis2-templates#3]
Maybe I'm not looking in the right place. The OneNote Notebook mentions Skype but does not include the IDs. Kindly avail these or point me to where they are stated.

**Comment by saragaudon** [comment]
Hi Adam! Thank you for reporting these issues, and the solution you found. I've asked my colleague Nicholas to look into the errors so we can fix them. We will be in touch.


Sara


---
Sara Gaudon | Executive Director, LogicalOutcomes  |  www.logicaloutcomes.net<http://www.logicaloutcomes.net/>
Toronto (647) 478-5634 x103 Washington DC (202) 779-9634 ext 103 |  sara@logicaloutcomes.net
________________________________

**Comment by NicholasKoySantillo** [comment]
Hi @adam-je  - We use Skype to connect with team members or students when using the notebook, but have not included any Skype IDs in the public notebook.  Does this answer your question?

If you are looking to get in touch with team members from LogicalOutcomes, you can write me an email at: nicholas@logicaloutcomes.net

**Comment by adam-je** [comment]
Yes @NicholasKoySantillo , Thank you.
