### ISSUE TITLE
Project Management Notebook flagging a virus in Windows Defender

### ISSUE THREAD

**Issue by adam-je** [LogicalOutcomes/dhis2-templates#4]
Hello. Kindly note that Windows Defender is flagging the **Project Management Notebook** as a Trojan.

![project management notebook](https://cloud.githubusercontent.com/assets/7912989/16911301/f06dc3d0-4cdd-11e6-954b-366aea876e60.JPG)

**Comment by saragaudon** [comment]
Hi Adam - thank you for telling us; the file was certainly infected.


I've made a fresh file, posted, and was able to open with ease.


https://github.com/LogicalOutcomes/dhis2-templates/wiki/Project-Management-Notebook



---
Sara Gaudon | Executive Director, LogicalOutcomes  |  www.logicaloutcomes.net<http://www.logicaloutcomes.net/>
Toronto (647) 478-5634 x103 Washington DC (202) 779-9634 ext 103 |  sara@logicaloutcomes.net
________________________________

**Comment by adam-je** [comment]
It's fixed!

Wow, that was quick Sara, Thanks!
